/* eslint-disable @typescript-eslint/no-explicit-any */
import {
    Activity,
    Archive,
    Bell,
    BellRing,
    Binary,
    Blocks,
    Boxes,
    Braces,
    Bug,
    Building2,
    Cable,
    CalendarClock,
    ChartBar,
    ChartLine,
    Clock,
    Cloud,
    CloudCog,
    Cog,
    Combine,
    Compass,
    Container,
    Cookie,
    Copy,
    Cpu,
    CreditCard,
    Database,
    DoorOpen,
    EthernetPort,
    FileCode,
    FileKey,
    Fingerprint,
    FolderTree,
    Gauge,
    GitBranch,
    GitFork,
    Globe,
    Handshake,
    HardDrive,
    Image,
    Inbox,
    Key,
    KeyRound,
    Layers,
    Layers2,
    LayoutGrid,
    LifeBuoy,
    Link,
    ListChecks,
    Lock,
    Mail,
    MapPin,
    MemoryStick,
    MessageSquare,
    Microchip,
    Network,
    Orbit,
    Package,
    Pin,
    Puzzle,
    Rabbit,
    Radio,
    Recycle,
    RefreshCw,
    Repeat,
    Rocket,
    Route,
    Router,
    Scale,
    ScrollText,
    Search,
    Send,
    Server,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Ship,
    Shuffle,
    Siren,
    Smartphone,
    Split,
    Terminal,
    Ticket,
    Timer,
    TrendingUp,
    Triangle,
    Undo2,
    Unlink,
    Upload,
    UserCheck,
    Users,
    Vault,
    Waves,
    Waypoints,
    Webhook,
    Workflow,
    Zap,
} from 'lucide-react';

/**
 * A single lesson of the DevOps track. Same shape as a System Design topic,
 * plus an optional `group` used by modules that bundle their lessons into
 * sub-sections (Module 14).
 */
export interface DevOpsLesson {
    id: string;
    title: string;
    icon?: any;
    tag?: string;
    time?: string;
    level?: string;
    type?: string;
    summary?: string;
    details?: string;
    useCases?: string[];
    practice?: string[];
    tools?: string[];
    /** Sub-section heading inside a module. */
    group?: string;
}

export interface DevOpsModule {
    id: string;
    title: string;
    /** Bengali name, kept separate so no dash is needed to join them. */
    subtitle?: string;
    duration: string;
    topics: DevOpsLesson[];
}

/** Landing page copy for the track. */
export const devopsTrack = {
    slug: 'devops',
    badge: 'DevOps & Internet',
    title: 'DevOps & Internet From Scratch',
    subtitle: 'From Browser to Production Infrastructure',
    description:
        'এই Curriculum-এর লক্ষ্য শুধু DevOps শেখানো না। Docker command মুখস্থ করা নয়। যেকোনো Architecture Diagram দেখে বোঝা যে কেন এই Component এখানে আছে, Request কোথা দিয়ে যায়, এবং Production-এ সবকিছু কীভাবে একসাথে কাজ করে।',
    goals: [
        'Internet কীভাবে কাজ করে সেটা ভিতর থেকে বোঝা',
        'Browser থেকে Request Database পর্যন্ত পুরো Journey ব্যাখ্যা করা',
        'DNS, TCP, HTTP, HTTPS, TLS, Reverse Proxy নিজের ভাষায় বোঝানো',
        'VPS-এ Production-ready Backend Deploy করা',
        'Docker Networking বোঝা',
        'Cloudflare, CDN, Edge, Vercel, Load Balancer একসাথে কীভাবে কাজ করে বোঝা',
        'CI/CD Pipeline তৈরি করা',
        'Production Infrastructure Design করা',
        'Kubernetes, AWS, GCP শেখার জন্য শক্ত ভিত্তি তৈরি করা',
    ],
    lessonSteps: [
        {
            title: 'Theory',
            description: 'কেন এই জিনিসটা দরকার। সমস্যাটা আগে, সমাধান পরে।',
        },
        {
            title: 'Visual Explanation',
            description: 'ASCII Diagram আর Flow Chart দিয়ে ছবি হিসেবে দেখা।',
        },
        {
            title: 'Real Example',
            description: 'বাস্তব জীবনের একটা উদাহরণ, যেটা মনে থাকবে।',
        },
        {
            title: 'Project Example',
            description: 'Island Tours-এ এই জিনিসটা ঠিক কোথায় ঘটছে।',
        },
        {
            title: 'Hands-on',
            description: 'Linux বা VPS-এ নিজে হাতে করে দেখা।',
        },
        {
            title: 'Quiz',
            description: '৫-১০টা Conceptual Question দিয়ে যাচাই।',
        },
        {
            title: 'Assignment',
            description: 'একটা ছোট Practical Task, যেটা জমা দেওয়া যায়।',
        },
        {
            title: 'Recap',
            description: '৫ মিনিটে পুরো Lesson-এর Revision।',
        },
    ],
    /** What every lesson document must ship with, beyond the 8 steps above. */
    lessonDeliverables: [
        'Real-life Example: গল্পের মতো বাস্তব উদাহরণ',
        'Sketch Diagram: হাতে আঁকা ছবির মতো পরিষ্কার',
        'Step-by-step Request Flow: ধাপে ধাপে পুরো যাত্রা',
        'Animation Story: চোখের সামনে চলতে দেখা',
        'Hands-on Lab: নিজে হাতে করে দেখা',
        'Mini Project: ছোট কিন্তু সম্পূর্ণ কাজ',
        'Best Video Resources: বাছাই করা ভিডিও আর আর্টিকেল',
    ],
    outcomes: [
        'Architecture Diagram নিখুঁতভাবে পড়তে ও ডিজাইন করতে পারা',
        'Production System আত্মবিশ্বাসের সাথে Debug করা',
        'VPS থেকে Cloud Infrastructure, ইনস অ্যান্ড আউটস জানা',
        'যেকোনো High-end Interview Board-এ Networking ও DevOps-এ লিড নেওয়া',
    ],
};

export const devopsCourseData: DevOpsModule[] = [
    {
        id: 'computer-fundamentals',
        title: 'Computer Fundamentals',
        subtitle: 'কম্পিউটার বেসিক',
        duration: '৫-৭ দিন',
        topics: [
            {
                id: 'binary-and-data',
                title: 'Binary, Bit and Byte',
                icon: Binary,
                tag: 'START HERE',
                time: '১৫-২০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'কম্পিউটার সব কিছু ০ আর ১ দিয়ে রাখে। Bit, Byte আর Data আসলে কী।',
            },
            {
                id: 'cpu-basics',
                title: 'CPU: How a Processor Thinks',
                icon: Microchip,
                tag: 'FOUNDATION',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'CPU একটার পর একটা Instruction চালায়। Clock, Core আর Cache এর ভূমিকা।',
            },
            {
                id: 'memory-and-ram',
                title: 'RAM, Stack and Heap',
                icon: MemoryStick,
                tag: 'FOUNDATION',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Program চলার সময় Data কোথায় থাকে। RAM, Stack আর Heap এর পার্থক্য।',
            },
            {
                id: 'storage-basics',
                title: 'Storage: HDD, SSD and Filesystem',
                icon: HardDrive,
                tag: 'FOUNDATION',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'RAM আর Disk আলাদা কেন, আর Filesystem কীভাবে File খুঁজে পায়।',
            },
            {
                id: 'operating-system-basics',
                title: 'What an Operating System Actually Does',
                icon: Cog,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Kernel, User Space আর System Call। OS আসলে কী কাজ করে।',
            },
            {
                id: 'process-vs-thread',
                title: 'Process, Thread and Concurrency',
                icon: Split,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'Process আর Thread আলাদা কীভাবে, আর একসাথে অনেক কাজ চলে কীভাবে।',
            },
            {
                id: 'how-a-program-runs',
                title: 'How a Program Actually Runs',
                icon: Terminal,
                tag: 'BIG PICTURE',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Deep Dive',
                summary:
                    'Code লেখা থেকে CPU-তে চলা পর্যন্ত একটা Program এর পুরো যাত্রা।',
            },
        ],
    },
    {
        id: 'internet-fundamentals',
        title: 'Internet Fundamentals',
        subtitle: 'ইন্টারনেটের ভিত্তি',
        duration: '৫-৭ দিন',
        topics: [
            {
                id: 'what-is-internet',
                title: 'Internet কী?',
                icon: Globe,
                tag: 'START HERE',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Internet আসলে কী। Cable, ISP আর Protocol-এর একটা বিশাল নেটওয়ার্ক কীভাবে এক হলো।',
            },
            {
                id: 'client-server-isp',
                title: 'Client, Server, and ISP',
                icon: Server,
                tag: 'BASICS',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Client কে Request পাঠায়, Server কে উত্তর দেয়, আর ISP মাঝখানে ঠিক কী করে।',
            },
            {
                id: 'os-networking',
                title: 'OS Networking',
                icon: Cpu,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'আপনার Operating System-এর ভেতরে Network Stack, Socket আর Port কীভাবে কাজ করে।',
            },
            {
                id: 'packet-latency-bandwidth',
                title: 'Packet, Latency, and Bandwidth',
                icon: Gauge,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Data ছোট ছোট Packet-এ ভাগ হয়, আর Latency আর Bandwidth কখনোই এক জিনিস না।',
            },
            {
                id: 'how-data-travels',
                title: 'How Data Travels Across The Internet',
                icon: Route,
                tag: 'VISUAL',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Submarine Cable থেকে Router Hop, Data আসলে কোন পথ ধরে গন্তব্যে পৌঁছায়।',
            },
            {
                id: 'end-to-end-request-journey',
                title: 'End-to-End Request Journey',
                icon: Waypoints,
                tag: 'BIG PICTURE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Browser-এ URL লেখা থেকে Database পর্যন্ত, পুরো Request Journey একসাথে।',
            },
        ],
    },
    {
        id: 'computer-networking',
        title: 'Computer Networking',
        subtitle: 'কম্পিউটার নেটওয়ার্কিং',
        duration: '১-২ সপ্তাহ',
        topics: [
            {
                id: 'network-basics',
                title: 'Network Basics (LAN, WAN, MAN)',
                icon: Network,
                tag: 'BASICS',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'LAN, WAN, MAN। কোন Network কতটুকু এলাকা জুড়ে থাকে আর কেন।',
            },
            {
                id: 'router-switch-hub',
                title: 'Router, Switch, and Hub',
                icon: Router,
                tag: 'HARDWARE',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'Router, Switch আর Hub। তিনটার কাজ আলাদা, কোনটা কোথায় লাগে।',
            },
            {
                id: 'mac-address',
                title: 'MAC Address',
                icon: Fingerprint,
                tag: 'CORE',
                time: '১৫-২০ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'প্রতিটা Network Card-এর নিজস্ব Hardware Address কীভাবে কাজ করে।',
            },
            {
                id: 'arp-protocol',
                title: 'ARP: IP to MAC Resolution',
                icon: Cable,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Networking',
                summary:
                    'IP জানা আছে, কিন্তু Frame পাঠাতে MAC দরকার। ARP সেই অনুবাদটা করে।',
            },
            {
                id: 'ip-address',
                title: 'IP Address (IPv4 vs IPv6)',
                icon: MapPin,
                tag: 'MUST KNOW',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'IPv4 আর IPv6 এর গঠন, পার্থক্য আর কেন IPv6 দরকার হয়ে পড়ল।',
            },
            {
                id: 'public-vs-private-ip',
                title: 'Public IP vs Private IP',
                icon: Split,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'আপনার Laptop-এর IP আর Internet-এ দেখানো IP আলাদা হয় কেন।',
            },
            {
                id: 'subnet-mask',
                title: 'Subnet Mask',
                icon: LayoutGrid,
                tag: 'HANDS-ON',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Networking',
                summary:
                    'Subnet Mask দিয়ে একটা বড় Network-কে ছোট ছোট ভাগে ভাগ করা।',
            },
            {
                id: 'gateway',
                title: 'Gateway',
                icon: DoorOpen,
                tag: 'CORE',
                time: '১৫-২০ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'Local Network থেকে বাইরে বেরোনোর দরজা, Default Gateway এর কাজ।',
            },
            {
                id: 'dhcp',
                title: 'DHCP',
                icon: Handshake,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Networking',
                summary:
                    'নতুন Device Network-এ ঢুকলে IP কে দেয় আর কীভাবে দেয়।',
            },
            {
                id: 'nat-pat',
                title: 'NAT & PAT',
                icon: Shuffle,
                tag: 'DEEP DIVE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Networking',
                summary:
                    'একটা Public IP-র পেছনে শত শত Device কীভাবে একসাথে চলে।',
            },
            {
                id: 'phone-internet-connection',
                title: 'How Your Phone Connects To Internet',
                icon: Smartphone,
                tag: 'REAL WORLD',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Case Walkthrough',
                summary:
                    'Mobile Data আর WiFi, আপনার ফোন আসলে কীভাবে Internet-এ যুক্ত হয়।',
            },
        ],
    },
    {
        id: 'dns',
        title: 'DNS',
        subtitle: 'ডোমেইন নেম সিস্টেম',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'what-is-dns',
                title: 'What is DNS?',
                icon: Globe,
                tag: 'START HERE',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Domain Name থেকে IP Address, Internet-এর Phonebook কীভাবে কাজ করে।',
            },
            {
                id: 'domain-registrar-registry',
                title: 'Domain, Registrar, and Registry',
                icon: ScrollText,
                tag: 'BASICS',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Domain কেনার পেছনে Registrar, Registry আর ICANN এর ভূমিকা।',
            },
            {
                id: 'root-tld-authoritative-dns',
                title: 'Root Server, TLD, and Authoritative DNS',
                icon: Network,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'Root Server থেকে TLD হয়ে Authoritative Server, DNS এর ধাপগুলো।',
            },
            {
                id: 'recursive-resolver',
                title: 'Recursive Resolver',
                icon: Search,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'Resolver কীভাবে আপনার হয়ে পুরো DNS Chain ঘুরে উত্তর নিয়ে আসে।',
            },
            {
                id: 'dns-cache-ttl',
                title: 'DNS Cache & TTL',
                icon: Timer,
                tag: 'PRACTICAL',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'TTL কী, Cache কোথায় কোথায় জমে আর কেন পুরনো IP দেখা যায়।',
            },
            {
                id: 'dns-records',
                title: 'DNS Records (A, AAAA, CNAME, MX, TXT, NS, SRV)',
                icon: ListChecks,
                tag: 'MUST KNOW',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'A, AAAA, CNAME, MX, TXT, NS, SRV। কোন Record ঠিক কী কাজ করে।',
            },
            {
                id: 'cloudflare-dns',
                title: 'Cloudflare DNS',
                icon: Cloud,
                tag: 'HANDS-ON',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Nameserver বদল, Proxy Mode আর DNS Only এর পার্থক্য হাতে-কলমে।',
            },
            {
                id: 'dns-propagation',
                title: 'DNS Propagation',
                icon: Orbit,
                tag: 'PRACTICAL',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'DNS বদলালে সেটা সবার কাছে পৌঁছাতে সময় লাগে কেন।',
            },
            {
                id: 'dns-journey',
                title: 'Complete DNS Journey',
                icon: Route,
                tag: 'BIG PICTURE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'একটা Domain Request-এর সম্পূর্ণ DNS Journey ধাপে ধাপে।',
            },
        ],
    },
    {
        id: 'tcp-ip',
        title: 'TCP/IP & Transport Layer',
        subtitle: 'ট্রান্সপোর্ট লেয়ার',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'osi-model',
                title: 'OSI Model',
                icon: Layers,
                tag: 'FOUNDATION',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'সাত Layer-এর OSI Model, প্রতিটা Layer আসলে কী দায়িত্ব নেয়।',
            },
            {
                id: 'tcp-ip-model',
                title: 'TCP/IP Model',
                icon: Layers2,
                tag: 'FOUNDATION',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'বাস্তবে ব্যবহৃত চার Layer-এর TCP/IP Model আর OSI এর সাথে তুলনা।',
            },
            {
                id: 'tcp-deep-dive',
                title: 'TCP Deep Dive',
                icon: Handshake,
                tag: 'DEEP DIVE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Reliable Connection, Sequence Number, Retransmission আর Flow Control।',
            },
            {
                id: 'udp-deep-dive',
                title: 'UDP Deep Dive',
                icon: Zap,
                tag: 'DEEP DIVE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Connectionless, দ্রুত কিন্তু Unreliable। UDP ঠিক কোথায় ব্যবহার হয়।',
            },
            {
                id: 'three-way-handshake',
                title: 'Three-way Handshake (SYN, SYN-ACK, ACK)',
                icon: Repeat,
                tag: 'MUST KNOW',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'SYN, SYN-ACK, ACK। একটা Connection তৈরি হওয়ার তিন ধাপ।',
            },
            {
                id: 'packet-segment-frame',
                title: 'Packet, Segment, and Frame',
                icon: Package,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'একই Data প্রতিটা Layer-এ কোন নামে আর কোন মোড়কে যায়।',
            },
            {
                id: 'port-and-socket',
                title: 'Port & Socket',
                icon: EthernetPort,
                tag: 'CORE',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'Port Number, Socket আর একই Server-এ অনেক Service একসাথে চালানো।',
            },
            {
                id: 'connection-close',
                title: 'Connection Close (FIN, ACK)',
                icon: Unlink,
                tag: 'DETAIL',
                time: '১৫-২০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'FIN, ACK আর TIME_WAIT। Connection ভদ্রভাবে বন্ধ করার নিয়ম।',
            },
        ],
    },
    {
        id: 'http-https',
        title: 'HTTP & HTTPS',
        subtitle: 'ওয়েব প্রোটোকল',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'url-vs-uri',
                title: 'URL vs URI',
                icon: Link,
                tag: 'BASICS',
                time: '১৫-২০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'URL, URI আর URN। Scheme, Host, Path, Query কীভাবে সাজানো থাকে।',
            },
            {
                id: 'http-basics',
                title: 'HTTP Protocol Basics',
                icon: Globe,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Request-Response Model, Stateless মানে কী আর HTTP Version-গুলোর গল্প।',
            },
            {
                id: 'http-methods-status-codes',
                title: 'HTTP Methods & Status Codes',
                icon: ListChecks,
                tag: 'MUST KNOW',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory & Lab',
                summary:
                    'GET, POST, PUT, PATCH, DELETE আর 2xx থেকে 5xx এর আসল মানে।',
            },
            {
                id: 'http-headers',
                title: 'HTTP Headers',
                icon: FileCode,
                tag: 'PRACTICAL',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Request-Response Header, Content-Type, Cache-Control আর CORS Header।',
            },
            {
                id: 'cookies',
                title: 'Cookies',
                icon: Cookie,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'Cookie কীভাবে সেট হয় আর HttpOnly, Secure, SameSite কেন জরুরি।',
            },
            {
                id: 'session-vs-jwt',
                title: 'Session vs JWT',
                icon: KeyRound,
                tag: 'HIGH IMPACT',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Server Session আর JWT। কোনটা কখন, আর Trade-off ঠিক কোথায়।',
            },
            {
                id: 'https-tls-ssl',
                title: 'HTTPS, TLS, and SSL',
                icon: Lock,
                tag: 'CRITICAL',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'TLS Handshake, Encryption আর HTTPS আসলে কোন জিনিসটা রক্ষা করে।',
            },
            {
                id: 'certificates-keys',
                title: 'Certificates, Public Key, and Private Key',
                icon: FileKey,
                tag: 'CRITICAL',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'Public Key, Private Key, CA আর Chain of Trust কীভাবে বিশ্বাস তৈরি করে।',
            },
            {
                id: 'https-journey',
                title: 'Full HTTPS Journey',
                icon: ShieldCheck,
                tag: 'BIG PICTURE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'একটা HTTPS Request-এর পুরো Journey, DNS থেকে Encrypted Response।',
            },
            {
                id: 'websocket-realtime',
                title: 'WebSocket & Real-time Communication',
                icon: MessageSquare,
                tag: 'REAL-TIME',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'HTTP Upgrade থেকে WebSocket, Server নিজে থেকে Message পাঠায় কীভাবে।',
            },
        ],
    },
    {
        id: 'linux-vps',
        title: 'Linux & VPS Fundamentals',
        subtitle: 'লিনাক্স ও ভিপিএস',
        duration: '১-২ সপ্তাহ',
        topics: [
            {
                id: 'linux-filesystem',
                title: 'Linux Filesystem Architecture',
                icon: FolderTree,
                tag: 'FOUNDATION',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Hands-on Lab',
                summary:
                    '/etc, /var, /usr, /home। Linux Filesystem-এর গঠন আর কোথায় কী থাকে।',
            },
            {
                id: 'process-management-systemd',
                title: 'Process Management & Systemd',
                icon: Cog,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Process, PID, Signal আর systemd দিয়ে Service চালু-বন্ধ রাখা।',
            },
            {
                id: 'ssh-security-keys',
                title: 'SSH & Security Keys',
                icon: Key,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Hands-on Lab',
                summary:
                    'SSH Key Pair বানানো, Password Login বন্ধ করা আর Server-এ নিরাপদে ঢোকা।',
            },
            {
                id: 'permissions-users-groups',
                title: 'Permissions, Users, and Groups',
                icon: Users,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Hands-on Lab',
                summary:
                    'chmod, chown, User আর Group। Permission ঠিকভাবে সাজানো।',
            },
            {
                id: 'environment-variables',
                title: 'Environment Variables',
                icon: Braces,
                tag: 'PRACTICAL',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Hands-on Lab',
                summary:
                    'Environment Variable, .env File আর Secret নিরাপদে রাখার নিয়ম।',
            },
            {
                id: 'firewall-ufw',
                title: 'Firewall Management (ufw)',
                icon: Shield,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'ufw দিয়ে Port খোলা-বন্ধ করা আর Server-এ Firewall Rule সাজানো।',
            },
            {
                id: 'system-logs',
                title: 'System Logs (journalctl, systemctl)',
                icon: ScrollText,
                tag: 'DEBUGGING',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'journalctl আর systemctl দিয়ে Log পড়ে আসল সমস্যা খুঁজে বের করা।',
            },
            {
                id: 'monitoring-tools',
                title: 'Monitoring Tools (top, htop)',
                icon: Activity,
                tag: 'OPS',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Hands-on Lab',
                summary:
                    'top, htop, df, free। Server-এর CPU, RAM, Disk এর অবস্থা পড়া।',
            },
            {
                id: 'network-debugging',
                title: 'Network Debugging (netstat, ss, curl)',
                icon: Bug,
                tag: 'DEBUGGING',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'netstat, ss, curl, dig দিয়ে Network সমস্যা ধাপে ধাপে Debug করা।',
            },
            {
                id: 'cron-jobs',
                title: 'Cron & Scheduled Tasks',
                icon: CalendarClock,
                tag: 'HANDS-ON',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Hands-on Lab',
                summary:
                    'crontab আর systemd timer দিয়ে নির্দিষ্ট সময়ে কাজ চালানো।',
            },
        ],
    },
    {
        id: 'backend-runtime',
        title: 'Backend Runtime',
        subtitle: 'Node.js ভেতর থেকে',
        duration: '১-২ সপ্তাহ',
        topics: [
            {
                id: 'nodejs-internals',
                title: 'Node.js Internals (V8 + libuv)',
                icon: Cpu,
                tag: 'DEEP DIVE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Node.js আসলে V8 আর libuv এর জোড়া, ভেতরে কে কী করে।',
            },
            {
                id: 'event-loop',
                title: 'The Event Loop, Phase by Phase',
                icon: Repeat,
                tag: 'MUST KNOW',
                time: '৬০-৯০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Timer, Poll, Check, Microtask। Event Loop প্রতিটা ধাপে কী করে।',
            },
            {
                id: 'libuv-threadpool',
                title: 'libuv, Thread Pool and Blocking Work',
                icon: Combine,
                tag: 'DEEP DIVE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'Single Thread হয়েও File আর Crypto কাজ কীভাবে সমান্তরালে চলে।',
            },
            {
                id: 'v8-and-gc',
                title: 'V8 Compilation & Garbage Collection',
                icon: Recycle,
                tag: 'PERFORMANCE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'JIT Compile, Hidden Class আর Garbage Collector Memory ফেরত নেয় কীভাবে।',
            },
            {
                id: 'streams-and-buffers',
                title: 'Streams and Buffers',
                icon: Waves,
                tag: 'HIGH IMPACT',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'বড় File বা Upload পুরোটা Memory-তে না নিয়ে টুকরো টুকরো সামলানো।',
            },
            {
                id: 'async-patterns',
                title: 'Callback, Promise and async/await Internals',
                icon: Workflow,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Async Code ভেতরে কীভাবে চলে আর Error কোথায় হারিয়ে যায়।',
            },
            {
                id: 'nodejs-performance',
                title: 'Cluster, Worker Threads and Memory Leaks',
                icon: Gauge,
                tag: 'PRODUCTION',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'সব CPU Core ব্যবহার করা আর Memory Leak ধরে ফেলা।',
            },
        ],
    },
    {
        id: 'backend-architecture',
        title: 'Backend Architecture',
        subtitle: 'NestJS ও API Layer',
        duration: '১-২ সপ্তাহ',
        topics: [
            {
                id: 'nestjs-internals',
                title: 'NestJS Internals (Module, Provider, Lifecycle)',
                icon: Blocks,
                tag: 'CORE',
                time: '৬০-৯০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Module, Provider, Controller আর Request Lifecycle ভেতর থেকে।',
            },
            {
                id: 'dependency-injection',
                title: 'Dependency Injection',
                icon: Puzzle,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'DI Container কীভাবে নিজে থেকে Dependency বসিয়ে দেয় আর কেন দরকার।',
            },
            {
                id: 'auth-implementation',
                title: 'Authentication in Practice (Session, JWT, Refresh)',
                icon: Key,
                tag: 'HIGH IMPACT',
                time: '৬০-৯০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Login থেকে Token Refresh, নিরাপদ Authentication বাস্তবায়ন।',
            },
            {
                id: 'authorization-rbac',
                title: 'Authorization (Roles, Permissions, Guards)',
                icon: UserCheck,
                tag: 'SECURITY',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'কে কী করতে পারবেন। Role, Permission আর Guard দিয়ে নিয়ন্ত্রণ।',
            },
            {
                id: 'backend-caching',
                title: 'Caching Inside the Application',
                icon: Zap,
                tag: 'PERFORMANCE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Response Cache, Redis Layer আর Cache Invalidation বাস্তবে।',
            },
            {
                id: 'backend-rate-limiting',
                title: 'Application Rate Limiting',
                icon: Gauge,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Proxy-র বাইরে App Level-এ Token Bucket দিয়ে Limit বসানো।',
            },
            {
                id: 'queues-and-workers',
                title: 'Queues and Worker Processes',
                icon: Inbox,
                tag: 'MUST KNOW',
                time: '৬০-৯০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'ভারী কাজ Queue-তে পাঠিয়ে Worker দিয়ে করানো, Retry আর DLQ।',
            },
            {
                id: 'background-jobs-scheduling',
                title: 'Background Jobs & Scheduling',
                icon: Clock,
                tag: 'PRACTICAL',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Recurring Job, Delayed Job আর একই Job দুইবার না চালানোর উপায়।',
            },
        ],
    },
    {
        id: 'docker',
        title: 'Docker & Containerization',
        subtitle: 'কন্টেইনারাইজেশন',
        duration: '১-২ সপ্তাহ',
        topics: [
            {
                id: 'container-vs-vm',
                title: 'Container vs Virtual Machine',
                icon: Container,
                tag: 'FOUNDATION',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Container আর Virtual Machine। একইরকম দেখতে, ভেতরে সম্পূর্ণ আলাদা।',
            },
            {
                id: 'docker-images-layers',
                title: 'Images & Dockerfile Layers',
                icon: Layers,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Image, Layer, Build Cache আর Dockerfile লেখার সঠিক ক্রম।',
            },
            {
                id: 'volume-vs-bind-mount',
                title: 'Volume vs Bind Mount',
                icon: HardDrive,
                tag: 'PRACTICAL',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Container বন্ধ হলে Data কোথায় যায়, Volume আর Bind Mount এর পার্থক্য।',
            },
            {
                id: 'docker-networking',
                title: 'Docker Networking (Bridge, Host, Overlay)',
                icon: Network,
                tag: 'DEEP DIVE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'Bridge, Host আর Overlay Network। Container-রা কীভাবে কথা বলে।',
            },
            {
                id: 'docker-dns',
                title: 'DNS Resolution Inside Docker',
                icon: Globe,
                tag: 'DEBUGGING',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Container-এর ভেতর থেকে Service Name দিয়ে অন্য Container খুঁজে পাওয়া।',
            },
            {
                id: 'docker-compose',
                title: 'Docker Compose for Multi-container Apps',
                icon: Boxes,
                tag: 'HANDS-ON',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'একাধিক Container একসাথে চালানো, Compose File-এর গঠন আর নিয়ম।',
            },
            {
                id: 'multi-stage-builds',
                title: 'Multi-stage Builds for Optimization',
                icon: Package,
                tag: 'OPTIMIZATION',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Build Stage আলাদা করে Image Size কয়েকগুণ কমিয়ে আনা।',
            },
        ],
    },
    {
        id: 'reverse-proxy',
        title: 'Reverse Proxy & Web Servers',
        subtitle: 'রিভার্স প্রক্সি',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'reverse-vs-forward-proxy',
                title: 'Reverse Proxy vs Forward Proxy',
                icon: Split,
                tag: 'FOUNDATION',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'Forward Proxy আর Reverse Proxy, কে আসলে কার হয়ে কথা বলে।',
            },
            {
                id: 'nginx-deep-dive',
                title: 'Nginx Deep Dive',
                icon: Server,
                tag: 'MUST KNOW',
                time: '৬০-৯০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Nginx Config এর গঠন। Server Block, Location আর Upstream।',
            },
            {
                id: 'caddy-server',
                title: 'Caddy (Automatic SSL & Modern Config)',
                icon: ShieldCheck,
                tag: 'MODERN',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Caddy দিয়ে Automatic HTTPS আর অল্প Config-এ Production Setup।',
            },
            {
                id: 'ssl-termination',
                title: 'SSL Termination',
                icon: Lock,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'SSL ঠিক কোথায় শেষ হয় আর Proxy-তে Certificate কীভাবে সামলানো হয়।',
            },
            {
                id: 'virtual-hosts',
                title: 'Virtual Hosts & Reverse Proxying',
                icon: Globe,
                tag: 'HANDS-ON',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'একই Server-এ একাধিক Domain আর Subdomain একসাথে চালানো।',
            },
            {
                id: 'proxy-rate-limiting-headers',
                title: 'Rate Limiting & Security Headers',
                icon: Gauge,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Rate Limit, Security Header আর Abuse থেকে বাঁচার Proxy Config।',
            },
            {
                id: 'compression-http2-http3',
                title: 'Compression & Modern Protocols (HTTP/2, HTTP/3)',
                icon: Zap,
                tag: 'PERFORMANCE',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Theory & Lab',
                summary:
                    'Gzip, Brotli আর HTTP/2, HTTP/3 দিয়ে Site অনেক দ্রুত করা।',
            },
        ],
    },
    {
        id: 'cloud-infrastructure',
        title: 'Cloud Infrastructure Concepts',
        subtitle: 'ক্লাউড ইনফ্রাস্ট্রাকচার',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'vps-vs-dedicated-vs-vm',
                title: 'VPS vs Dedicated Server vs VM',
                icon: Server,
                tag: 'FOUNDATION',
                time: '২০-৩০ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'VPS, Dedicated Server আর VM। কোনটা কখন দরকার আর খরচ কেমন।',
            },
            {
                id: 'hypervisors',
                title: 'Hypervisors',
                icon: Cpu,
                tag: 'THEORY',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'একটা Physical Machine থেকে অনেক Server, Hypervisor এর কাজ।',
            },
            {
                id: 'cdn-edge-computing',
                title: 'CDN & Edge Computing',
                icon: Globe,
                tag: 'HIGH IMPACT',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'CDN কীভাবে User-এর সবচেয়ে কাছের জায়গা থেকে Content দেয়।',
            },
            {
                id: 'edge-functions',
                title: 'Edge Functions',
                icon: Zap,
                tag: 'MODERN',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Theory & Lab',
                summary:
                    'Edge-এ Code চালানো, Latency কমানোর সবচেয়ে নতুন উপায়।',
            },
            {
                id: 'object-vs-block-storage',
                title: 'Object Storage (S3) vs Block Storage',
                icon: HardDrive,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'S3-এর মতো Object Storage আর Block Storage-এর আসল পার্থক্য।',
            },
            {
                id: 'managed-vs-selfhosted-db',
                title: 'Managed Database vs Self-hosted',
                icon: Database,
                tag: 'DECISION',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Trade-off Analysis',
                summary:
                    'Managed Database নেবেন নাকি নিজে Host করবেন, খরচ আর ঝুঁকির হিসাব।',
            },
            {
                id: 'serverless-architecture',
                title: 'Serverless Architecture',
                icon: CloudCog,
                tag: 'MODERN',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'Server নেই মানে কী, Cold Start কেন হয় আর Serverless এর সীমা কোথায়।',
            },
            {
                id: 'vercel-cloudflare-ecosystem',
                title: 'Vercel & Cloudflare Ecosystems',
                icon: Cloud,
                tag: 'PRACTICAL',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Ecosystem Tour',
                summary:
                    'Vercel আর Cloudflare এর Product-গুলো কোথায় কীভাবে ফিট করে।',
            },
            {
                id: 'transactional-email',
                title: 'Transactional Email (SMTP, SPF, DKIM, DMARC)',
                icon: Send,
                tag: 'PRACTICAL',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'App থেকে Email পাঠানো আর Spam Folder-এ না পড়ার জন্য SPF, DKIM, DMARC।',
            },
        ],
    },
    {
        id: 'scaling-ha',
        title: 'Scaling & High Availability',
        subtitle: 'স্কেলিং ও এইচএ',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'load-balancers-l4-l7',
                title: 'Load Balancers (Layer 4 vs Layer 7)',
                icon: Scale,
                tag: 'MUST KNOW',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Layer 4 আর Layer 7 Load Balancer, কোনটা কী দেখে সিদ্ধান্ত নেয়।',
            },
            {
                id: 'sticky-sessions',
                title: 'Sticky Sessions & Session Persistence',
                icon: Pin,
                tag: 'PRACTICAL',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'একই User বারবার একই Server-এ পাঠানো। কখন দরকার, কী সমস্যা।',
            },
            {
                id: 'horizontal-vs-vertical-scaling',
                title: 'Horizontal Scaling vs Vertical Scaling',
                icon: TrendingUp,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Beginner',
                type: 'Theory',
                summary:
                    'বড় Server নেবেন নাকি বেশি Server নেবেন, কখন কোনটা সঠিক।',
            },
            {
                id: 'health-checks-circuit-breakers',
                title: 'Health Checks & Circuit Breakers',
                icon: Activity,
                tag: 'RELIABILITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'অসুস্থ Server চিনে বাদ দেওয়া আর Cascading Failure থামানো।',
            },
            {
                id: 'auto-scaling',
                title: 'Auto Scaling Mechanics',
                icon: Gauge,
                tag: 'CLOUD',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Theory',
                summary:
                    'Traffic বাড়লে Server নিজে নিজে বাড়ে, ভেতরের হিসাবটা কী।',
            },
            {
                id: 'high-availability',
                title: 'High Availability (HA) Systems',
                icon: ShieldCheck,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Architecture',
                summary:
                    '99.9% Uptime মানে কী আর একটা HA Setup আসলে কেমন দেখতে হয়।',
            },
            {
                id: 'failover-strategies',
                title: 'Failover Strategies',
                icon: RefreshCw,
                tag: 'PRODUCTION',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Architecture',
                summary:
                    'Primary পড়ে গেলে কে দায়িত্ব নেবে, Failover Plan সাজানো।',
            },
        ],
    },
    {
        id: 'databases-caching',
        title: 'Advanced Databases & Caching',
        subtitle: 'ডেটাবেস ও ক্যাশিং',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'postgresql-internals',
                title: 'PostgreSQL Networking & Internals',
                icon: Database,
                tag: 'DEEP DIVE',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'PostgreSQL Connection, WAL আর Query Execution ভেতর থেকে দেখা।',
            },
            {
                id: 'mvcc-postgres',
                title: 'MVCC, Vacuum and Bloat',
                icon: Layers2,
                tag: 'DEEP DIVE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                summary:
                    'PostgreSQL একই Row-এর অনেক Version রাখে কেন। MVCC, Vacuum আর Table Bloat।',
            },
            {
                id: 'connection-pooling-pgbouncer',
                title: 'Connection Pooling & PgBouncer',
                icon: Combine,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Connection শেষ হয়ে যাওয়ার সমস্যা আর PgBouncer এর সমাধান।',
            },
            {
                id: 'redis-overview',
                title: 'Redis Overview',
                icon: Zap,
                tag: 'MUST KNOW',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Redis কী, কোন Data Structure আছে আর কোথায় ব্যবহার করবেন।',
            },
            {
                id: 'caching-strategies',
                title: 'Caching Strategies (Cache Aside, Write Through)',
                icon: Cpu,
                tag: 'HIGH IMPACT',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Deep Dive',
                summary:
                    'Cache Aside, Write Through, Write Back। কোনটা কখন বেছে নেবেন।',
            },
            {
                id: 'read-replicas-lag',
                title: 'Read Replicas & Replication Lag',
                icon: Copy,
                tag: 'SCALING',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Theory & Lab',
                summary:
                    'Read Replica দিয়ে Load ভাগ করা আর Replication Lag এর ফাঁদ।',
            },
            {
                id: 'backup-restore-automation',
                title: 'Backup & Restore Automation',
                icon: Archive,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Automated Backup, Restore Test আর Data হারানো থেকে বাঁচার নিয়ম।',
            },
        ],
    },
    {
        id: 'cicd',
        title: 'CI/CD & Production Deployment',
        subtitle: 'সিআই/সিডি',
        duration: '১-২ সপ্তাহ',
        topics: [
            {
                id: 'git-flow-trunk-based',
                title: 'Git Flow & Trunk-Based Development',
                icon: GitBranch,
                tag: 'WORKFLOW',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'Git Flow আর Trunk-Based Development, Team-এ আসলে কোনটা কাজ করে।',
            },
            {
                id: 'github-actions',
                title: 'GitHub Actions Pipelines',
                icon: Workflow,
                tag: 'HANDS-ON',
                time: '৬০-৯০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Workflow, Job, Step আর Runner দিয়ে নিজের Pipeline বানানো।',
            },
            {
                id: 'docker-registries',
                title: 'Docker Registries (GHCR, DockerHub)',
                icon: Package,
                tag: 'HANDS-ON',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'Image Build করে GHCR বা DockerHub-এ Push আর Pull করা।',
            },
            {
                id: 'environment-management',
                title: 'Environment Management (Dev, Staging, Production)',
                icon: Braces,
                tag: 'WORKFLOW',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory & Lab',
                summary:
                    'তিনটা Environment আলাদা রাখা আর Config কোথায় কীভাবে বদলায়।',
            },
            {
                id: 'rolling-deployment',
                title: 'Deployment Strategy: Rolling',
                icon: RefreshCw,
                tag: 'STRATEGY',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'ধীরে ধীরে Instance বদলে নতুন Version Production-এ আনা।',
            },
            {
                id: 'blue-green-deployment',
                title: 'Deployment Strategy: Blue-Green',
                icon: Split,
                tag: 'STRATEGY',
                time: '২০-৩০ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                summary:
                    'দুইটা Environment রেখে এক Switch-এ Release আর সাথে সাথে Rollback।',
            },
            {
                id: 'canary-deployment',
                title: 'Deployment Strategy: Canary',
                icon: Rabbit,
                tag: 'STRATEGY',
                time: '২০-৩০ মিনিট',
                level: 'Advanced',
                type: 'Theory',
                summary:
                    'অল্প Traffic দিয়ে নতুন Version আগে পরীক্ষা করে নেওয়া।',
            },
            {
                id: 'rollback-strategies',
                title: 'Rollback & Failed Deploy Recovery',
                icon: Undo2,
                tag: 'STRATEGY',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Reliability',
                summary:
                    'Deploy ভেঙে গেলে দ্রুত পিছিয়ে আসা, Rollback Plan আর Database এর ফাঁদ।',
            },
            {
                id: 'pipeline-secrets-management',
                title: 'Secrets Management in Pipelines',
                icon: Vault,
                tag: 'SECURITY',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Pipeline-এ Secret নিরাপদে রাখা আর Log-এ ভুলেও ফাঁস না করা।',
            },
        ],
    },
    {
        id: 'observability',
        title: 'Observability',
        subtitle: 'Monitoring ও Debugging',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'observability-basics',
                title: 'The Three Pillars: Logs, Metrics, Traces',
                icon: Activity,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Ops & Monitoring',
                summary:
                    'Log, Metric আর Trace। Production-এ কী হচ্ছে বোঝার তিন স্তম্ভ।',
            },
            {
                id: 'structured-logging',
                title: 'Structured Logging & Log Aggregation',
                icon: ScrollText,
                tag: 'HANDS-ON',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'JSON Log, Correlation ID আর সব Server-এর Log এক জায়গায় আনা।',
            },
            {
                id: 'metrics-prometheus',
                title: 'Metrics with Prometheus',
                icon: ChartLine,
                tag: 'HANDS-ON',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Counter, Gauge, Histogram আর Prometheus কীভাবে Metric জমা করে।',
            },
            {
                id: 'grafana-dashboards',
                title: 'Dashboards with Grafana',
                icon: ChartBar,
                tag: 'HANDS-ON',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Hands-on Lab',
                summary:
                    'যে Dashboard দেখে সত্যিই সিদ্ধান্ত নেওয়া যায়, সেটা বানানো।',
            },
            {
                id: 'distributed-tracing',
                title: 'Distributed Tracing (OpenTelemetry, Jaeger)',
                icon: Route,
                tag: 'DEEP DIVE',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'একটা Request কোন Service-এ কত সময় নিল, Trace করে বের করা।',
            },
            {
                id: 'alerting-systems',
                title: 'Alerting Without Alert Fatigue',
                icon: Bell,
                tag: 'PRODUCTION',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Ops & Monitoring',
                summary:
                    'কোন Alert সত্যিই দরকার আর রাত ৩টায় কোনটা বাজা উচিত না।',
            },
        ],
    },
    {
        id: 'island-tours-case-study',
        title: 'Case Study: Island Tours Production',
        subtitle: 'কেস স্টাডি',
        duration: '১ সপ্তাহ',
        topics: [
            {
                id: 'island-cloudflare-routing',
                title: 'Domain Routing via Cloudflare',
                icon: Cloud,
                tag: 'CASE STUDY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Case Study',
                summary:
                    'Island Tours-এর Domain কীভাবে Cloudflare দিয়ে Route করা হয়েছে।',
            },
            {
                id: 'island-edge-cdn-caching',
                title: 'Edge CDN & Caching Rules',
                icon: Globe,
                tag: 'CASE STUDY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Case Study',
                summary:
                    'কোন Content Edge-এ Cache হয়, কোন Rule-এ আর কেন।',
            },
            {
                id: 'island-vercel-frontend',
                title: 'Vercel Frontend Deployment Mechanics',
                icon: Rocket,
                tag: 'CASE STUDY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Case Study',
                summary:
                    'Frontend Vercel-এ Deploy হওয়ার সময় ভেতরে ঠিক কী ঘটে।',
            },
            {
                id: 'island-vps-setup',
                title: 'VPS (Hostinger) Infrastructure Configuration',
                icon: Server,
                tag: 'CASE STUDY',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Case Study',
                summary:
                    'Hostinger VPS-এ User, Firewall আর Base Setup কীভাবে সাজানো হলো।',
            },
            {
                id: 'island-caddy-ssl',
                title: 'Caddy Reverse Proxy & SSL Automation',
                icon: Lock,
                tag: 'CASE STUDY',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Case Study',
                summary:
                    'Caddy Reverse Proxy আর Automatic SSL কীভাবে বসানো হয়েছে।',
            },
            {
                id: 'island-dockerized-nestjs',
                title: 'Dockerized NestJS Application Management',
                icon: Container,
                tag: 'CASE STUDY',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Case Study',
                summary:
                    'NestJS API Docker-এ চালানো, Restart আর Log সামলানোর নিয়ম।',
            },
            {
                id: 'island-redis-postgres',
                title: 'Redis & PostgreSQL Integration',
                icon: Database,
                tag: 'CASE STUDY',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Case Study',
                summary:
                    'Redis আর PostgreSQL Container-এর সাথে API এর সংযোগ কীভাবে হয়।',
            },
            {
                id: 'island-cicd-pipeline',
                title: 'CI/CD Pipeline Automation',
                icon: Workflow,
                tag: 'CASE STUDY',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Case Study',
                summary:
                    'Push করলে Production পর্যন্ত পৌঁছানোর পুরো Automation।',
            },
            {
                id: 'island-backup-monitoring',
                title: 'Automated Backups & Monitoring Setup',
                icon: Archive,
                tag: 'CASE STUDY',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Case Study',
                summary:
                    'Automated Backup আর Monitoring কীভাবে বসানো হলো।',
            },
            {
                id: 'island-architecture-review',
                title: 'Final Architecture Review',
                icon: Compass,
                tag: 'REVIEW',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Architecture Review',
                summary:
                    'পুরো Architecture আবার পড়া। এখানে Request কেন গেল, এই Component কেন দরকার।',
            },
        ],
    },
    {
        id: 'advanced-infrastructure',
        title: 'Advanced Infrastructure & Distributed Systems',
        subtitle: 'অ্যাডভান্সড ইনফ্রা',
        duration: '৩-৪ সপ্তাহ',
        topics: [
            {
                id: 'database-indexing',
                title: 'Database Indexing & Query Optimization',
                icon: Search,
                tag: 'HIGH IMPACT',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                group: 'Database Scaling',
                summary:
                    'Index কীভাবে কাজ করে আর কোন Query-তে কোন Index দরকার।',
            },
            {
                id: 'execution-plans',
                title: 'Execution Plans & Query Performance',
                icon: Gauge,
                tag: 'HANDS-ON',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                group: 'Database Scaling',
                summary:
                    'EXPLAIN পড়ে Slow Query-র আসল কারণটা বের করে আনা।',
            },
            {
                id: 'acid-isolation-levels',
                title: 'ACID Transactions & Isolation Levels',
                icon: Lock,
                tag: 'THEORY',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                group: 'Database Scaling',
                summary:
                    'ACID আসলে কী আর Isolation Level বদলালে কী কী ঘটে।',
            },
            {
                id: 'database-locks',
                title: 'Database Locks (Optimistic vs Pessimistic, Deadlocks)',
                icon: KeyRound,
                tag: 'DEEP DIVE',
                time: '৪৫-৬০ মিনিট',
                level: 'Expert',
                type: 'Deep Dive',
                group: 'Database Scaling',
                summary:
                    'Optimistic আর Pessimistic Lock, আর Deadlock কীভাবে তৈরি হয়।',
            },
            {
                id: 'database-replication',
                title: 'Database Replication (Read Replica, Multi-Primary)',
                icon: Copy,
                tag: 'SCALING',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Architecture',
                group: 'Advanced Database Architecture',
                summary:
                    'Read Replica আর Multi-Primary Replication এর গঠন ও ঝুঁকি।',
            },
            {
                id: 'database-partitioning',
                title: 'Database Partitioning (Vertical vs Horizontal)',
                icon: Split,
                tag: 'SCALING',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Architecture',
                group: 'Advanced Database Architecture',
                summary:
                    'Vertical আর Horizontal Partitioning, কখন সত্যিই দরকার হয়।',
            },
            {
                id: 'database-sharding-consistent-hashing',
                title: 'Database Sharding & Consistent Hashing',
                icon: Boxes,
                tag: 'EXPERT',
                time: '৬০-৯০ মিনিট',
                level: 'Expert',
                type: 'Architecture',
                group: 'Advanced Database Architecture',
                summary:
                    'Shard ভাগ করা আর Consistent Hashing এর পেছনের গণিত।',
            },
            {
                id: 'cap-theorem-deep-dive',
                title: 'CAP Theorem Deep Dive',
                icon: Triangle,
                tag: 'THEORY',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                group: 'Distributed Systems',
                summary:
                    'Consistency, Availability, Partition Tolerance। বাস্তব Trade-off।',
            },
            {
                id: 'consistency-models',
                title: 'Eventual Consistency vs Strong Consistency',
                icon: Scale,
                tag: 'THEORY',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Deep Dive',
                group: 'Distributed Systems',
                summary:
                    'Strong আর Eventual Consistency, User আসলে কী অনুভব করে।',
            },
            {
                id: 'distributed-caching',
                title: 'Distributed Caching',
                icon: Cpu,
                tag: 'SCALING',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Architecture',
                group: 'Distributed Systems',
                summary:
                    'একাধিক Node জুড়ে Cache, Invalidation আর Hot Key সমস্যা।',
            },
            {
                id: 'message-queues-basics',
                title: 'Message Queues (RabbitMQ, Kafka Basics)',
                icon: Mail,
                tag: 'MUST KNOW',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Async Systems',
                group: 'Distributed Systems',
                summary:
                    'RabbitMQ আর Kafka, Queue আর Stream এর মৌলিক পার্থক্য।',
            },
            {
                id: 'event-driven-architecture',
                title: 'Event-Driven Architecture (EDA)',
                icon: Radio,
                tag: 'ARCHITECTURE',
                time: '৬০-৯০ মিনিট',
                level: 'Expert',
                type: 'Architecture',
                group: 'Distributed Systems',
                summary:
                    'Event দিয়ে Service আলাদা রাখা, সুবিধা আর লুকানো জটিলতা।',
            },
            {
                id: 'network-vs-object-storage',
                title: 'Network Storage vs Object Storage (S3)',
                icon: HardDrive,
                tag: 'CORE',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Theory',
                group: 'Storage & Security',
                summary:
                    'NFS-এর মতো Network Storage আর S3 Object Storage-এর পার্থক্য।',
            },
            {
                id: 'file-storage-asset-delivery',
                title: 'File Storage & Asset Delivery (S3 + CDN)',
                icon: Image,
                tag: 'PRACTICAL',
                time: '৩০-৪৫ মিনিট',
                level: 'Intermediate',
                type: 'Architecture',
                group: 'Storage & Security',
                summary:
                    'Local, File আর Object Storage কখন কোনটা, আর Asset CDN দিয়ে সার্ভ করা।',
            },
            {
                id: 'auth-oauth-oidc',
                title: 'Authentication & Authorization (OAuth 2.0, OIDC, API Keys)',
                icon: KeyRound,
                tag: 'SECURITY',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Security',
                group: 'Storage & Security',
                summary:
                    'OAuth 2.0, OIDC আর API Key। কে আসলে কী প্রমাণ করে।',
            },
            {
                id: 'web-security-practices',
                title: 'Security Best Practices (CORS, CSRF, XSS, SQL Injection)',
                icon: ShieldAlert,
                tag: 'CRITICAL',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'Security',
                group: 'Storage & Security',
                summary:
                    'CORS, CSRF, XSS আর SQL Injection থেকে বাঁচার বাস্তব নিয়ম।',
            },
            {
                id: 'enterprise-secrets-management',
                title: 'Enterprise Secrets Management',
                icon: Vault,
                tag: 'SECURITY',
                time: '৪৫-৬০ মিনিট',
                level: 'Expert',
                type: 'Security',
                group: 'Storage & Security',
                summary:
                    'Vault আর KMS দিয়ে Secret Rotate করা আর Audit রাখা।',
            },
            {
                id: 'zero-downtime-deployments',
                title: 'Zero Downtime Deployments',
                icon: RefreshCw,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Expert',
                type: 'Reliability',
                group: 'Production Reliability & Cloud Foundations',
                summary:
                    'Database Migration সহ Deploy করেও Downtime শূন্য রাখা।',
            },
            {
                id: 'disaster-recovery',
                title: 'Disaster Recovery Strategies (RPO/RTO)',
                icon: LifeBuoy,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Expert',
                type: 'Reliability',
                group: 'Production Reliability & Cloud Foundations',
                summary:
                    'RPO আর RTO ঠিক করে একটা কাজের Disaster Recovery Plan বানানো।',
            },
            {
                id: 'incident-response-slo',
                title: 'Incident Response, SLAs, SLOs, and Error Budgets',
                icon: Siren,
                tag: 'PRODUCTION',
                time: '৪৫-৬০ মিনিট',
                level: 'Expert',
                type: 'Reliability',
                group: 'Production Reliability & Cloud Foundations',
                summary:
                    'Incident সামলানো আর SLA, SLO, Error Budget এর হিসাব রাখা।',
            },
            {
                id: 'cloud-providers-overview',
                title: 'Cloud Providers Overview (AWS, GCP, Azure)',
                icon: Cloud,
                tag: 'OVERVIEW',
                time: '৪৫-৬০ মিনিট',
                level: 'Intermediate',
                type: 'Ecosystem Tour',
                group: 'Production Reliability & Cloud Foundations',
                summary:
                    'AWS, GCP আর Azure এর মূল Service-গুলো এক নজরে, নাম গুলিয়ে না ফেলে।',
            },
        ],
    },
    {
        id: 'kubernetes',
        title: 'Kubernetes',
        subtitle: 'Container Orchestration',
        duration: '২ সপ্তাহ',
        topics: [
            {
                id: 'kubernetes-introduction',
                title: 'Why Kubernetes Exists',
                icon: Boxes,
                tag: 'NEXT STEP',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Theory',
                summary:
                    'Docker Compose যেখানে থেমে যায়, Kubernetes সেখান থেকে কী করে।',
            },
            {
                id: 'k8s-pods',
                title: 'Pods and Containers',
                icon: Container,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Pod কী, একের ভেতর অনেক Container আর Sidecar Pattern।',
            },
            {
                id: 'k8s-deployments',
                title: 'Deployments and ReplicaSets',
                icon: RefreshCw,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Replica ঠিক রাখা আর Rolling Update দিয়ে নতুন Version আনা।',
            },
            {
                id: 'k8s-services',
                title: 'Services (ClusterIP, NodePort, LoadBalancer)',
                icon: Network,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Pod বদলে গেলেও একটা স্থির ঠিকানা, Service কীভাবে দেয়।',
            },
            {
                id: 'k8s-ingress',
                title: 'Ingress and TLS Routing',
                icon: DoorOpen,
                tag: 'CORE',
                time: '৪৫-৬০ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'বাইরের Traffic Cluster-এ ঢোকার দরজা আর HTTPS সামলানো।',
            },
            {
                id: 'k8s-configmap-secret',
                title: 'ConfigMap and Secret',
                icon: FileKey,
                tag: 'PRACTICAL',
                time: '৩০-৪৫ মিনিট',
                level: 'Advanced',
                type: 'Hands-on Lab',
                summary:
                    'Config আর Secret Image থেকে আলাদা রেখে Pod-এ পৌঁছে দেওয়া।',
            },
            {
                id: 'helm-basics',
                title: 'Helm Basics',
                icon: Ship,
                tag: 'PRACTICAL',
                time: '৪৫-৬০ মিনিট',
                level: 'Expert',
                type: 'Hands-on Lab',
                summary:
                    'Helm Chart দিয়ে একই Deployment বারবার, অনেক Environment-এ।',
            },
        ],
    },
    {
        id: 'applied-system-design',
        title: 'Applied System Design',
        subtitle: 'বাস্তব Feature Design',
        duration: '২-৩ সপ্তাহ',
        topics: [
            {
                id: 'design-auth-system',
                title: 'Design an Authentication System',
                icon: KeyRound,
                tag: 'CAPSTONE',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'System Design Case',
                summary:
                    'Signup থেকে Session, Refresh আর Device Logout। পুরো Auth Flow ডিজাইন।',
            },
            {
                id: 'design-file-upload',
                title: 'Design a File Upload Pipeline',
                icon: Upload,
                tag: 'CAPSTONE',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'System Design Case',
                summary:
                    'Presigned URL, Validation, Processing আর CDN Delivery একসাথে।',
            },
            {
                id: 'design-payment-flow',
                title: 'Design a Payment Flow',
                icon: CreditCard,
                tag: 'CAPSTONE',
                time: '৬০-৯০ মিনিট',
                level: 'Expert',
                type: 'System Design Case',
                summary:
                    'Idempotency, Webhook আর টাকা দুইবার না কাটার নিশ্চয়তা।',
            },
            {
                id: 'design-notification-system',
                title: 'Design a Notification System',
                icon: BellRing,
                tag: 'CAPSTONE',
                time: '৬০-৯০ মিনিট',
                level: 'Advanced',
                type: 'System Design Case',
                summary:
                    'Email, Push, SMS আর In-app। একটা Notification Service ডিজাইন।',
            },
            {
                id: 'design-booking-system',
                title: 'Design a Booking System (Island Tours)',
                icon: Ticket,
                tag: 'CAPSTONE',
                time: '৯০-১২০ মিনিট',
                level: 'Expert',
                type: 'System Design Case',
                summary:
                    'Seat Lock, Double Booking আর Payment Timeout সহ Booking Flow।',
            },
            {
                id: 'design-multi-tenancy',
                title: 'Design Multi-tenancy',
                icon: Building2,
                tag: 'CAPSTONE',
                time: '৬০-৯০ মিনিট',
                level: 'Expert',
                type: 'System Design Case',
                summary:
                    'একই App-এ অনেক Client, Data আলাদা রাখার তিনটা কৌশল।',
            },
            {
                id: 'design-microservices-migration',
                title: 'Monolith to Microservices Migration',
                icon: GitFork,
                tag: 'CAPSTONE',
                time: '৯০-১২০ মিনিট',
                level: 'Expert',
                type: 'System Design Case',
                summary:
                    'কোন অংশ আগে আলাদা করবেন আর Migration-এর সময় সব কিছু চালু রাখা।',
            },
            {
                id: 'design-event-driven-system',
                title: 'Design an Event-Driven System',
                icon: Webhook,
                tag: 'CAPSTONE',
                time: '৯০-১২০ মিনিট',
                level: 'Expert',
                type: 'System Design Case',
                summary:
                    'Event, Consumer আর Replay। বাস্তব Event-driven Architecture ডিজাইন।',
            },
        ],
    },
];

/** Every lesson in track order, for prev/next, sitemap and static params. */
export const devopsLessons: DevOpsLesson[] = devopsCourseData.flatMap(
    section => section.topics
);

/** Look up a lesson together with the module it belongs to. */
export function findDevopsLesson(id: string) {
    const section = devopsCourseData.find(m =>
        m.topics.some(t => t.id === id)
    );
    if (!section) return null;
    const lesson = section.topics.find(t => t.id === id);
    if (!lesson) return null;
    return { module: section, lesson };
}
